openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Delivery
paths:
  /api/v1/orders/active:
    get:
      summary: Получить все незавершенные заказы
      description: Позволяет получить все незавершенные
      operationId: GetOrders
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        default:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Location:
      allOf:
        - required:
            - x
            - y
          properties:
            x:
              type: integer
              description: X
            y:
              type: integer
              description: Y
    Order:
      allOf:
        - required:
            - id
            - location
          properties:
            id:
              type: string
              format: uuid
              description: Идентификатор
            location:
              $ref: '#/components/schemas/Location'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Код ошибки
        message:
          type: string
          description: Текст ошибки
