openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Delivery
paths:
  /api/v1/couriers/:
    get:
      summary: Получить всех курьеров
      description: Позволяет получить всех курьеров
      operationId: GetCouriers
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                required:
                  - couriers
                properties:
                  couriers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Courier'
        default:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Location:
      allOf:
        - required:
            - x
            - y
          properties:
            x:
              type: integer
              description: X
            y:
              type: integer
              description: Y
    Courier:
      allOf:
        - required:
            - id
            - name
            - location
          properties:
            id:
              type: string
              format: uuid
              description: Идентификатор
            name:
              description: Имя
              type: string
            location:
              $ref: '#/components/schemas/Location'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Код ошибки
        message:
          type: string
          description: Текст ошибки
